nginx:
    build: ./nginx/
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app

php:
    build: ./php/
    expose:
        - 9000
    links:
        - mysql
    volumes_from:
        - app

app:
    image: php:7.0-fpm
    volumes:
        - .:/var/www/html
    command: "true"

mysql:
    image: mysql:latest
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: iaisrr_db
        MYSQL_USER: iaisrr_user
        MYSQL_PASSWORD: iaisrr_password

redis:
    build: ./redis
    volumes_from:
        - data
    ports:
        - 6379:6379

beanstalkd:
    build: ./beanstalkd
    ports:
        - 11300:11300
    privileged: true
    links:
        - php

beanstalkd-console:
    build: ./beanstalkd-console
    ports:
        - 2080:2080
    links:
        - beanstalkd

data:
    image: mysql:latest
    volumes:
        - /var/lib/mysql
    command: "true"